name: 'Parse publish tag from Git tag'
description: 'Extracts semver version and npm publish tag from GitHub tag'
author: 'Yuki'
inputs:
  prefix:
    description: 'Prefix to strip from tag (e.g. v, release-'
    required: false
    default: 'v'
outputs:
  tag:
    description: "NPM publish tag (e.g. latest, beta)"
  full:
    description: "Semantic version and build"
  version:
    description: "Full semantic version (e.g. 1.2.3-beta.1)"
  major:
    description: "Major version number"
  minor:
    description: "Minor version number"
  patch:
    description: "Patch version number"
  build:
    description: "Build version number"
runs:
  using: node20
  main: ./dist/index.cjs
branding:
  icon: "tag"
  color: "green"